/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_cloud_aerospike_BackupReader */

#ifndef _Included_com_google_cloud_aerospike_BackupReader
#define _Included_com_google_cloud_aerospike_BackupReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_cloud_aerospike_BackupReader
 * Method:    openFile
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_google_cloud_aerospike_BackupReader_openFile
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_google_cloud_aerospike_BackupReader
 * Method:    closeFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_cloud_aerospike_BackupReader_closeFile
  (JNIEnv *, jobject);

/*
 * Class:     com_google_cloud_aerospike_BackupReader
 * Method:    readRecord
 * Signature: (Ljava/lang/String;)Lcom/google/cloud/aerospike/ReadRecordResult;
 */
JNIEXPORT jobject JNICALL Java_com_google_cloud_aerospike_BackupReader_readRecord
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
