name: Cassandra Proxy Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cassandra-bigtable-migration-tools/cassandra-bigtable-proxy/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test $(go list ./... | grep -v /testing/) # Run all unit tests (except testing/ because it requires external deps)