name: Kafka Connect Bigtable Sink CI

on:
  push:
    branches:
      - main
    paths:
      - "kafka-connect-bigtable-sink/**"
  pull_request:
    paths:
      - "kafka-connect-bigtable-sink/**"
  release:
    types: [published]

jobs:
  ci:
    name: Check the Kafka Connect Bigtable Sink code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Formatter
        working-directory: kafka-connect-bigtable-sink
        run: mvn -B -ntp spotless:check

      - name: Unit tests
        working-directory: kafka-connect-bigtable-sink
        run: mvn clean test -pl sink -am -B -ntp

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: latest
          install_components: beta,bigtable

      - name: Integration tests against the emulator
        working-directory: kafka-connect-bigtable-sink
        run: |
          set -euo pipefail
          gcloud beta emulators bigtable start --host-port=0.0.0.0:8086 &
          BIGTABLE_EMULATOR_HOST=localhost:8086 mvn -Pintegration-tests -B -ntp verify

  upload-release-asset:
    name: Upload Fat Jar to Release
    needs: ci
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to upload files to a GitHub release

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Fat Jar
        working-directory: kafka-connect-bigtable-sink
        run: mvn -B -ntp clean package -DskipTests

      - name: Upload Artifact to Release
        working-directory: kafka-connect-bigtable-sink
        env:
          # The standard GITHUB_TOKEN has permission to do this because of the `permissions` block above
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BINARY_NAME="cassandra-proxy-${{ matrix.os }}-${{ matrix.arch }}"

          # Use the GitHub CLI to upload the built binary to the release that triggered the workflow
          gh release upload ${{ github.event.release.tag_name }} ./sink/target/kafka-connect-bigtable-sink.jar --clobber